### ISSUE TITLE
Pretrained Model Checkpoints

### ISSUE THREAD

**Issue by jinny1208** [JoungheeKim/K-wav2vec#1]
Hi. I was wondering whether the pretrained checkpoint for K-wav2vec 2.0 was going to be released (the one that was further pretrained on the English checkpoint). 

Thanks in advance.

**Comment by JoungheeKim** [comment]
Hi.
Thank you for your interest.

I upload further pretrained checkpoint and edit my README.md file.
So, please check `README.md` again.

If you have any problem, please let me know.
Thank you.
