### ISSUE TITLE
Implementation of  Character-level Error Rate (CER) metric

### ISSUE THREAD

**Issue by ddehun** [JoungheeKim/K-wav2vec#5]
안녕하세요. 좋은 연구를 공유해주셔서 감사드립니다.

논문에 report된 CER 점수를 계산하기 위한 구현이 어느 부분인지 확실하지 않아 질문드립니다.

추측컨데 inference.py에서 아래의 부분인 것 같은데요, 

https://github.com/JoungheeKim/K-wav2vec/blob/main/inference/beam_search.py#L227

혹시 이처럼 editdistance library의 editdistance.eval() 함수를 사용하고, 함수의 입력으로는 음절 단위로 normalize된 두 개의 string이 사용된게 맞을까요?

감사합니다.

**Comment by JoungheeKim** [comment]
네 맞습니다.
